[programs.localnet]
staking = "3pccTEiGB8ZRdYX7FShPYRy1ZzQjdFASKSvNNbNduTxr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/<your username>/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
